### ISSUE TITLE
Add to unpacked.cern.ch

### ISSUE THREAD

**Issue by nsmith-** [CoffeaTeam/docker-coffea-base#5]
Following https://awesome-workshop.github.io/docker-singularity-hats/12-unpacked/index.html
looks like we just have to make a PR to https://gitlab.cern.ch/unpacked/sync to add these images there, which would allow singularity to use these containers directly from cvmfs

**Comment by oshadura** [comment]
Oh, seems nice!!! Why not?

**Comment by nsmith-** [comment]
I made a PR https://gitlab.cern.ch/unpacked/sync/-/merge_requests/70

**Comment by oshadura** [comment]
(and Jakob merged it, coool!)

**Comment by nsmith-** [comment]
Works for me: ```singularity shell -B ${PWD}:/work /cvmfs/unpacked.cern.ch/registry.hub.docker.com/coffeateam/coffea-dask:latest```
I'd call this closed, though we might want to go back and add all version at some point, instead of just `latest`.
