### ISSUE TITLE
dask_jobqueue in CalVer Images

### ISSUE THREAD

**Issue by rpsimeon34** [CoffeaTeam/docker-coffea-base#96]
Hi all,

I'm switching over to coffea v2024, and I noticed that the image I'm using (coffeateam/coffea-base:v2024.1.2) does not have the dask_joqueue package by default. We use dask_jobqueue.HTCondorCluster to create Clients, so that's a required package for us.

I added it in my own Dockerfile, but is there a reason for it to not be included in future coffea-base images? Thank you!

**Comment by oshadura** [comment]
We are slightly redoing coffea images, see https://github.com/CoffeaTeam/af-images/pull/1

So hopefully you will have everything you will need after this pull request is merged.

**Comment by rpsimeon34** [comment]
Thanks for the pointer! I'll consider the discussion moved over there.
